version: '3'

services:
    web-app:
        build: ./
        container_name: web-app
        restart: always
        ports:
            - "${APP_PORT}:8080"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/php/fpm-pool.conf:/usr/local/etc/php-fpm.d/fpm-pool.conf
            - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
        networks:
            - 'jetstream'

    front-app:
        image: node:20.6.1-alpine3.18
        container_name: front-app
        restart: always
        working_dir: /app
        entrypoint: /app/etc/bin/start-front.sh
        ports:
            - "5173:5173"
        volumes:
            - './:/app'
        networks:
            - 'jetstream'

    mongo:
        image: mongo:5.0
        container_name: mongodb
        restart: unless-stopped
        ports:
            - ${MONGODB_PORT}:27017
        networks:
            - 'jetstream'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
        volumes:
            - mongodata:/data/db

    mongo-express:
        image: mongo-express:1-20-alpine3.18
        container_name: mongo-express
        restart: unless-stopped
        depends_on:
            - 'mongo'
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        ports:
            - "8888:8081"
        networks:
            - 'jetstream'

networks:
    jetstream:
        driver: bridge

volumes:
    mongodata:
        driver: local
